### ISSUE TITLE
Systemtray icon still showing when program closed

### ISSUE THREAD

**Issue by attuo** [attuo/ClipboardHelper#2]
Quite usual problem, but it has some fixes available.

**Comment by keesvv** [comment]
@attuo I can try to solve this problem. Is this project still being maintained?

**Comment by attuo** [comment]
Hi! Thanks for your interest. Currently I'm too busy to maintain this project, so your help is more than welcome.

**Comment by keesvv** [comment]
@attuo Thank you, this is one of my first PR's.

I have built the solution and ran it, but I noticed that quitting through the application menu or right-clicking the tray icon _will_ remove the tray icon from the taskbar.

Do you mean that this problem occurs when the application is force closed? (through Task Manager, or Stop Debugging in Visual Studio)

**Comment by attuo** [comment]
This project has been on freeze for two years, so my recall might be a bit hazy. But this problem might not occur when you are using it on debug mode in Visual Studio. You might try the built .exe that I have provided here on github: [link](https://github.com/attuo/ClipboardHelper/releases/tag/1.1).
Compare that version to your debugging version, if that behaves differently than the one that you can debug on Visual Studio. 
If they behave exactly same, then at least you are sure, that your debugging in Visual Studio behaves correctly and you can trust that. 

And getting back to your question. I'm not entirely sure anymore when this problem occurs, but I think the problem occurred when quitting the program **via the application menu**, _but not always_. 

**AND** as you can see, this is an important learning opportunity for me, and maybe for you. Always try to explain your bugs very comprehensively, so it is understandable and someone else can repeat the process how to make the bug occur. My earlier "2-version-of-me" was clearly too busy to write proper bug issues, lol.

**Comment by keesvv** [comment]
@attuo I have double checked both my forked solution + your provided binary, and exiting the program through the application menu and through right-clicking the NotifyIcon in the taskbar tray, and I am a 100% sure that the NotifyIcon disappears after _every_ graceful exit, except for quitting through Task Manager.

I've searched on the internet, but unfortunately, I couldn't find any solution that removes the icon after force quitting the program trough Task Manager or using `taskkill /im ClipboardHelper.exe`.

If you are sure this problem isn't occurring anymore, maybe you should consider closing this issue.
N.B.: it was fun contributing! 😄

**Comment by attuo** [comment]
Well I'm glad to hear that. Thanks for using your time for investigating this bug :+1: 

So, there were no problem in code and you didn't have to make any changes?

**Comment by keesvv** [comment]
@attuo The only change I made on my own solution was to **update all dependencies** through NuGet Package Manager. But I didn't change anything in the code, and both versions acted normal. I only updated the dependencies, because VS2017 was throwing errors at me for missing libraries, so I updated them all and then I could finally debug the solution.

There is a very small chance, you might never know, that the update fixed the problem, but I'm not really sure with that.

**Comment by attuo** [comment]
Ok, thanks for the info. The dependency updates might or might not be the fix for this. All in all, it is clear that this bug only occurs when killing the program the "hard way", which is fine. 

Thanks for contributing! I mark this issue now closed.
